// Mocks generated by Mockito 5.4.4 from annotations
// in lab11and12/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i2;

import 'package:bloc/bloc.dart' as _i19;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:firebase_remote_config/firebase_remote_config.dart' as _i14;
import 'package:lab11and12/bloc/appBLoC.dart' as _i17;
import 'package:lab11and12/bloc/appEvent.dart' as _i18;
import 'package:lab11and12/bloc/appState.dart' as _i7;
import 'package:lab11and12/models/bookModel.dart' as _i8;
import 'package:lab11and12/models/favoriteModel.dart' as _i11;
import 'package:lab11and12/models/userModel.dart' as _i12;
import 'package:lab11and12/services/analyticsService.dart' as _i6;
import 'package:lab11and12/services/authService.dart' as _i13;
import 'package:lab11and12/services/connectivityService.dart' as _i20;
import 'package:lab11and12/services/databaseService.dart' as _i5;
import 'package:lab11and12/services/firestoreService.dart' as _i9;
import 'package:lab11and12/services/hiveService.dart' as _i16;
import 'package:lab11and12/services/remoteConfigService.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeColor_0 extends _i1.SmartFake implements _i2.Color {
  _FakeColor_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserMetadata_1 extends _i1.SmartFake implements _i3.UserMetadata {
  _FakeUserMetadata_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactor_2 extends _i1.SmartFake implements _i3.MultiFactor {
  _FakeMultiFactor_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdTokenResult_3 extends _i1.SmartFake implements _i3.IdTokenResult {
  _FakeIdTokenResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_4 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_5 extends _i1.SmartFake
    implements _i3.ConfirmationResult {
  _FakeConfirmationResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_6 extends _i1.SmartFake implements _i3.User {
  _FakeUser_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteConfigService_7 extends _i1.SmartFake
    implements _i4.RemoteConfigService {
  _FakeRemoteConfigService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseService_8 extends _i1.SmartFake
    implements _i5.DatabaseService {
  _FakeDatabaseService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalyticsService_9 extends _i1.SmartFake
    implements _i6.AnalyticsService {
  _FakeAnalyticsService_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppState_10 extends _i1.SmartFake implements _i7.AppState {
  _FakeAppState_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBook_11 extends _i1.SmartFake implements _i8.Book {
  _FakeBook_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i9.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> enableOfflinePersistence() => (super.noSuchMethod(
        Invocation.method(
          #enableOfflinePersistence,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Stream<List<_i8.Book>> getBooksStream() => (super.noSuchMethod(
        Invocation.method(
          #getBooksStream,
          [],
        ),
        returnValue: _i10.Stream<List<_i8.Book>>.empty(),
      ) as _i10.Stream<List<_i8.Book>>);

  @override
  _i10.Future<List<_i8.Book>> getBooks() => (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
        ),
        returnValue: _i10.Future<List<_i8.Book>>.value(<_i8.Book>[]),
      ) as _i10.Future<List<_i8.Book>>);

  @override
  _i10.Future<_i8.Book?> getBook(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBook,
          [id],
        ),
        returnValue: _i10.Future<_i8.Book?>.value(),
      ) as _i10.Future<_i8.Book?>);

  @override
  _i10.Future<void> addBook(_i8.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #addBook,
          [book],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateBook(_i8.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #updateBook,
          [book],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBook(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [bookId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Stream<List<_i11.Favorite>> getFavoritesStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoritesStream,
          [userId],
        ),
        returnValue: _i10.Stream<List<_i11.Favorite>>.empty(),
      ) as _i10.Stream<List<_i11.Favorite>>);

  @override
  _i10.Future<List<_i11.Favorite>> getFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue: _i10.Future<List<_i11.Favorite>>.value(<_i11.Favorite>[]),
      ) as _i10.Future<List<_i11.Favorite>>);

  @override
  _i10.Future<void> addToFavorites(
    String? userId,
    String? bookId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [
            userId,
            bookId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeFromFavorites(
    String? userId,
    String? bookId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [
            userId,
            bookId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isBookInFavorites(
    String? userId,
    String? bookId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isBookInFavorites,
          [
            userId,
            bookId,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> addUser(_i12.User? user) => (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i12.User?> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i10.Future<_i12.User?>.value(),
      ) as _i10.Future<_i12.User?>);

  @override
  _i10.Future<void> updateUser(_i12.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i13.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i3.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i10.Stream<_i3.User?>.empty(),
      ) as _i10.Stream<_i3.User?>);

  @override
  _i10.Future<_i12.User?> signUpWithEmail({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [],
          {
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i10.Future<_i12.User?>.value(),
      ) as _i10.Future<_i12.User?>);

  @override
  _i10.Future<_i12.User?> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i10.Future<_i12.User?>.value(),
      ) as _i10.Future<_i12.User?>);

  @override
  _i10.Future<_i12.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i10.Future<_i12.User?>.value(),
      ) as _i10.Future<_i12.User?>);

  @override
  _i10.Future<_i12.User?> signInWithGitHub() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGitHub,
          [],
        ),
        returnValue: _i10.Future<_i12.User?>.value(),
      ) as _i10.Future<_i12.User?>);

  @override
  _i10.Future<_i12.User?> signInWithMicrosoft() => (super.noSuchMethod(
        Invocation.method(
          #signInWithMicrosoft,
          [],
        ),
        returnValue: _i10.Future<_i12.User?>.value(),
      ) as _i10.Future<_i12.User?>);

  @override
  _i10.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i5.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> setUserOnline(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserOnline,
          [userId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setUserOffline(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserOffline,
          [userId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Stream<Map<String, dynamic>?> getUserStatusStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStatusStream,
          [userId],
        ),
        returnValue: _i10.Stream<Map<String, dynamic>?>.empty(),
      ) as _i10.Stream<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserStatus(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStatus,
          [userId],
        ),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> initializeUserStatus() => (super.noSuchMethod(
        Invocation.method(
          #initializeUserStatus,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i6.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> logBookView(
    String? bookId,
    String? bookTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logBookView,
          [
            bookId,
            bookTitle,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logBookLiked(
    String? bookId,
    String? bookTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logBookLiked,
          [
            bookId,
            bookTitle,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logBookUnliked(
    String? bookId,
    String? bookTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logBookUnliked,
          [
            bookId,
            bookTitle,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logSearch(String? searchQuery) => (super.noSuchMethod(
        Invocation.method(
          #logSearch,
          [searchQuery],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logLogin(String? method) => (super.noSuchMethod(
        Invocation.method(
          #logLogin,
          [method],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logSignUp(String? method) => (super.noSuchMethod(
        Invocation.method(
          #logSignUp,
          [method],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logBookCreated(
    String? bookId,
    String? bookTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logBookCreated,
          [
            bookId,
            bookTitle,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logBookDeleted(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #logBookDeleted,
          [bookId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logScreenView(String? screenName) => (super.noSuchMethod(
        Invocation.method(
          #logScreenView,
          [screenName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setUserProperty(
    String? name,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProperty,
          [
            name,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [RemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigService extends _i1.Mock
    implements _i4.RemoteConfigService {
  MockRemoteConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i14.RemoteConfigUpdate> get configUpdateStream =>
      (super.noSuchMethod(
        Invocation.getter(#configUpdateStream),
        returnValue: _i10.Stream<_i14.RemoteConfigUpdate>.empty(),
      ) as _i10.Stream<_i14.RemoteConfigUpdate>);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> fetchAndActivate() => (super.noSuchMethod(
        Invocation.method(
          #fetchAndActivate,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #getString,
            [key],
          ),
        ),
      ) as String);

  @override
  int getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValue: 0,
      ) as int);

  @override
  double getDouble(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [key],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  bool isLikeButtonEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLikeButtonEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.Color getBlockColor() => (super.noSuchMethod(
        Invocation.method(
          #getBlockColor,
          [],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getBlockColor,
            [],
          ),
        ),
      ) as _i2.Color);
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i16.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i12.User> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: <_i12.User>[],
      ) as List<_i12.User>);

  @override
  _i12.User? getUser(String? id) => (super.noSuchMethod(Invocation.method(
        #getUser,
        [id],
      )) as _i12.User?);

  @override
  _i10.Future<void> addUser(_i12.User? user) => (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i8.Book> getBooks() => (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
        ),
        returnValue: <_i8.Book>[],
      ) as List<_i8.Book>);

  @override
  _i8.Book? getBook(String? id) => (super.noSuchMethod(Invocation.method(
        #getBook,
        [id],
      )) as _i8.Book?);

  @override
  _i10.Future<void> addBook(_i8.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #addBook,
          [book],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateBook(_i8.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #updateBook,
          [book],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBook(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> replaceBooks(List<_i8.Book>? books) => (super.noSuchMethod(
        Invocation.method(
          #replaceBooks,
          [books],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i11.Favorite> getFavorites(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue: <_i11.Favorite>[],
      ) as List<_i11.Favorite>);

  @override
  _i10.Future<void> addToFavorites(
    String? userId,
    String? bookId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [
            userId,
            bookId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeFromFavorites(
    String? userId,
    String? bookId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [
            userId,
            bookId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool isBookInFavorites(
    String? userId,
    String? bookId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isBookInFavorites,
          [
            userId,
            bookId,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> replaceFavorites(
    String? userId,
    Iterable<String>? bookIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceFavorites,
          [
            userId,
            bookIds,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> demonstrateWrongKey() => (super.noSuchMethod(
        Invocation.method(
          #demonstrateWrongKey,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #demonstrateWrongKey,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> demonstrateWrongKeyOnBooks() => (super.noSuchMethod(
        Invocation.method(
          #demonstrateWrongKeyOnBooks,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #demonstrateWrongKeyOnBooks,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> compressData() => (super.noSuchMethod(
        Invocation.method(
          #compressData,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  Map<String, int> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified => (super.noSuchMethod(
        Invocation.getter(#emailVerified),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  _i3.UserMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeUserMetadata_1(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i3.UserMetadata);

  @override
  List<_i3.UserInfo> get providerData => (super.noSuchMethod(
        Invocation.getter(#providerData),
        returnValue: <_i3.UserInfo>[],
      ) as List<_i3.UserInfo>);

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i3.MultiFactor get multiFactor => (super.noSuchMethod(
        Invocation.getter(#multiFactor),
        returnValue: _FakeMultiFactor_2(
          this,
          Invocation.getter(#multiFactor),
        ),
      ) as _i3.MultiFactor);

  @override
  _i10.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [forceRefresh],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<_i3.IdTokenResult> getIdTokenResult(
          [bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdTokenResult,
          [forceRefresh],
        ),
        returnValue: _i10.Future<_i3.IdTokenResult>.value(_FakeIdTokenResult_3(
          this,
          Invocation.method(
            #getIdTokenResult,
            [forceRefresh],
          ),
        )),
      ) as _i10.Future<_i3.IdTokenResult>);

  @override
  _i10.Future<_i3.UserCredential> linkWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithCredential,
          [credential],
        ),
        returnValue:
            _i10.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithCredential,
            [credential],
          ),
        )),
      ) as _i10.Future<_i3.UserCredential>);

  @override
  _i10.Future<_i3.UserCredential> linkWithProvider(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithProvider,
          [provider],
        ),
        returnValue:
            _i10.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithProvider,
            [provider],
          ),
        )),
      ) as _i10.Future<_i3.UserCredential>);

  @override
  _i10.Future<_i3.UserCredential> reauthenticateWithProvider(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithProvider,
          [provider],
        ),
        returnValue:
            _i10.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithProvider,
            [provider],
          ),
        )),
      ) as _i10.Future<_i3.UserCredential>);

  @override
  _i10.Future<_i3.UserCredential> reauthenticateWithPopup(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithPopup,
          [provider],
        ),
        returnValue:
            _i10.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithPopup,
            [provider],
          ),
        )),
      ) as _i10.Future<_i3.UserCredential>);

  @override
  _i10.Future<void> reauthenticateWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithRedirect,
          [provider],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.UserCredential> linkWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPopup,
          [provider],
        ),
        returnValue:
            _i10.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithPopup,
            [provider],
          ),
        )),
      ) as _i10.Future<_i3.UserCredential>);

  @override
  _i10.Future<void> linkWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithRedirect,
          [provider],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i3.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i10.Future<_i3.ConfirmationResult>.value(_FakeConfirmationResult_5(
          this,
          Invocation.method(
            #linkWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i10.Future<_i3.ConfirmationResult>);

  @override
  _i10.Future<_i3.UserCredential> reauthenticateWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithCredential,
          [credential],
        ),
        returnValue:
            _i10.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithCredential,
            [credential],
          ),
        )),
      ) as _i10.Future<_i3.UserCredential>);

  @override
  _i10.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> sendEmailVerification(
          [_i3.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [actionCodeSettings],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.User> unlink(String? providerId) => (super.noSuchMethod(
        Invocation.method(
          #unlink,
          [providerId],
        ),
        returnValue: _i10.Future<_i3.User>.value(_FakeUser_6(
          this,
          Invocation.method(
            #unlink,
            [providerId],
          ),
        )),
      ) as _i10.Future<_i3.User>);

  @override
  _i10.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [newEmail],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updatePhoneNumber(
          _i3.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneNumber,
          [phoneCredential],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
        Invocation.method(
          #updatePhotoURL,
          [photoURL],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBeforeUpdateEmail,
          [
            newEmail,
            actionCodeSettings,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AppBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppBloc extends _i1.Mock implements _i17.AppBloc {
  MockAppBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RemoteConfigService get remoteConfigService => (super.noSuchMethod(
        Invocation.getter(#remoteConfigService),
        returnValue: _FakeRemoteConfigService_7(
          this,
          Invocation.getter(#remoteConfigService),
        ),
      ) as _i4.RemoteConfigService);

  @override
  _i5.DatabaseService get databaseService => (super.noSuchMethod(
        Invocation.getter(#databaseService),
        returnValue: _FakeDatabaseService_8(
          this,
          Invocation.getter(#databaseService),
        ),
      ) as _i5.DatabaseService);

  @override
  _i6.AnalyticsService get analyticsService => (super.noSuchMethod(
        Invocation.getter(#analyticsService),
        returnValue: _FakeAnalyticsService_9(
          this,
          Invocation.getter(#analyticsService),
        ),
      ) as _i6.AnalyticsService);

  @override
  _i7.AppState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAppState_10(
          this,
          Invocation.getter(#state),
        ),
      ) as _i7.AppState);

  @override
  _i10.Stream<_i7.AppState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<_i7.AppState>.empty(),
      ) as _i10.Stream<_i7.AppState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool isBookInFavorites(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #isBookInFavorites,
          [bookId],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i8.Book> getFavoriteBooks() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteBooks,
          [],
        ),
        returnValue: <_i8.Book>[],
      ) as List<_i8.Book>);

  @override
  _i8.Book createDemoBook({
    required String? title,
    required String? author,
    String? description = r'',
    String? imagePath = r'assets/default_book.jpg',
    double? rating = 0.0,
    int? reviewsCount = 0,
    List<String>? categories = const [],
    bool? isLiked = false,
    String? coverColor = r'0xFFd0c9b7',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDemoBook,
          [],
          {
            #title: title,
            #author: author,
            #description: description,
            #imagePath: imagePath,
            #rating: rating,
            #reviewsCount: reviewsCount,
            #categories: categories,
            #isLiked: isLiked,
            #coverColor: coverColor,
          },
        ),
        returnValue: _FakeBook_11(
          this,
          Invocation.method(
            #createDemoBook,
            [],
            {
              #title: title,
              #author: author,
              #description: description,
              #imagePath: imagePath,
              #rating: rating,
              #reviewsCount: reviewsCount,
              #categories: categories,
              #isLiked: isLiked,
              #coverColor: coverColor,
            },
          ),
        ),
      ) as _i8.Book);

  @override
  Map<String, int> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  _i10.Future<String> demonstrateEncryption() => (super.noSuchMethod(
        Invocation.method(
          #demonstrateEncryption,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #demonstrateEncryption,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  void add(_i18.AppEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i18.AppEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i7.AppState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i18.AppEvent>(
    _i19.EventHandler<E, _i7.AppState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i19.Transition<_i18.AppEvent, _i7.AppState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i19.Change<_i7.AppState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i20.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<bool> get connectivityStream => (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _i10.Stream<bool>.empty(),
      ) as _i10.Stream<bool>);

  @override
  _i10.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
